//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USBHelperLauncher.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("USBHelperLauncher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Loading {
            get {
                object obj = ResourceManager.GetObject("Loading", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {&quot;af-ZA&quot;: {&quot;name&quot;: &quot;Afrikaans&quot;, &quot;native&quot;: &quot;Afrikaans&quot;}, &quot;ar-SA&quot;: {&quot;name&quot;: &quot;Arabic&quot;, &quot;native&quot;: &quot;اللغة العربية&quot;}, &quot;ast-ES&quot;: {&quot;name&quot;: &quot;Asturian&quot;, &quot;native&quot;: &quot;Asturianu&quot;}, &quot;az-AZ&quot;: {&quot;name&quot;: &quot;Azerbaijani&quot;, &quot;native&quot;: &quot;Azərbaycanca&quot;}, &quot;ba-RU&quot;: {&quot;name&quot;: &quot;Bashkir&quot;, &quot;native&quot;: &quot;Башҡортса&quot;}, &quot;be-BY&quot;: {&quot;name&quot;: &quot;Belarusian&quot;, &quot;native&quot;: &quot;Беларуская&quot;}, &quot;bg-BG&quot;: {&quot;name&quot;: &quot;Bulgarian&quot;, &quot;native&quot;: &quot;Български&quot;}, &quot;br-FR&quot;: {&quot;name&quot;: &quot;Breton&quot;, &quot;native&quot;: &quot;Brezhoneg&quot;}, &quot;ca-ES&quot;: {&quot;name&quot;: &quot;Catalan&quot;, &quot;native&quot;: &quot;Català&quot;}, &quot;cs-CZ&quot;: {&quot;name&quot;:  [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string Locales {
            get {
                return ResourceManager.GetString("Locales", resourceCulture);
            }
        }
    }
}
