using Fiddler;
using System;
using System.Linq;
using System.Reflection;
using System.Xml.Linq;

namespace USBHelperLauncher.Net
{
    class SiteEndpoint : Endpoint
    {
        public SiteEndpoint() : base("www.wiiuusbhelper.com") { }

        [Request("/")]
        public void GetSite(Session oS)
        {
            XElement html = new XElement("html");
            html.Add(new XElement("a", "Site generated by Wii U USB Helper Launcher " + Program.GetVersion() + " on " + DateTime.Now.ToString()));
            html.Add(new XElement("br"));
            XElement list = new XElement("ul");
            foreach (var method in GetType().GetMethods())
            {
                Request request;
                if ((request = method.GetCustomAttributes().OfType<Request>().FirstOrDefault()) != null)
                {
                    XElement link = new XElement("a", method.Name);
                    link.SetAttributeValue("href", request.GetMask());
                    list.Add(new XElement("li", link));
                }
            }
            html.Add(list);
            oS.utilCreateResponseAndBypassServer();
            oS.utilSetResponseBody("<!DOCTYPE html>\n" + html.ToString());
        }

        [Request("/certificate")]
        public void GetCertificate(Session oS)
        {
            oS.utilCreateResponseAndBypassServer();
            oS.oResponse["Content-Type"] = "application/x-x509-ca-cert";
            oS.utilSetResponseBody("-----BEGIN CERTIFICATE-----\n" + Proxy.GetCertificateBase64() + "\n-----END CERTIFICATE----- ");
            Proxy.LogRequest(oS, this, "Sent certificate.");
        }

        [Request("/session")]
        public void GetSession(Session oS)
        {
            oS.utilCreateResponseAndBypassServer();
            oS.utilSetResponseBody(Program.GetSessionGuid().ToString());
            Proxy.LogRequest(oS, this, "Sent session guid.");
        }
    }
}
